### ISSUE TITLE
Build issue with OL3 after node js integration

### ISSUE THREAD

**Issue by Mahendershah** [openlayers/ol3#2196]
build.py build

I am getting error :

2014-05-29 14:43:03,792 build/exports.js: node tasks/generate-exports.js build/e
xports.js
Traceback (most recent call last):
  File "build.py", line 754, in <module>
    main()
  File "D:\Works\OL3Build\ol3\pake.py", line 442, in main
    target.build(dry_run=options.dry_run)
  File "D:\Works\OL3Build\ol3\pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "D:\Works\OL3Build\ol3\pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "D:\Works\OL3Build\ol3\pake.py", line 109, in build
    timestamp = max(timestamp, target.build(dry_run=dry_run))
  File "D:\Works\OL3Build\ol3\pake.py", line 124, in build
    self.action(self)
  File "build.py", line 177, in build_exports_js
    t.run('node', 'tasks/generate-exports.js', EXPORTS)
  File "D:\Works\OL3Build\ol3\pake.py", line 233, in run
    subprocess.check_call(args, **kwargs)
  File "d:\Works\OL3Build\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "d:\Works\OL3Build\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "d:\Works\OL3Build\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "d:\Works\OL3Build\Python27\lib\subprocess.py", line 957, in _execute_chi
ld
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

The environment details are :
Windows : Windows 7
Node Js : v0.10.24
OL3 Version : b6e0195c9bbb9bf07810b18ec2b59ea1a220b435

./build.py checkdeps is showing all dependency OK

Program "../Git/bin/git.exe" seems to be present.
Program "../Python27/Scripts/gjslint.exe" seems to be present.
Program "../jdk1.7.0_01/bin/java.exe" seems to be present.
Program "../jdk1.7.0_01/jre7/bin/jar.exe" seems to be present.
Program "./node_modules/.bin/jsdoc" seems to be present.
Program "./node_modules/.bin/jshint" seems to be present.
Program "../Python27/python.exe" seems to be present.
Program "./node_modules/.bin/phantomjs" seems to be present.
For certain targets all above programs need to be present.

One strange thing found while running npm install the jshint and phantomjs got included in nodemodules/.bin folder but I didn't found jsdoc. Since I already had the earlier jsdoc installed in my system, so I copied the jsdoc and jsdoc.cmd file in nodemodules/.bin folder. And thus the checkdeps earlier issue was corrected. But still I am getting this error.

Any clue ?

Thanks

**Comment by bartvde** [comment]
We have many open issues for the build on Windows already so closing this one as a duplicate
