### ISSUE TITLE
Building Ol3 in 2589 fails in Windows

### ISSUE THREAD

**Issue by Mahendershah** [openlayers/ol3#2592]
build.py build
2014-08-22 16:36:46,240 build/ol.css: D:\Works\OL3Build\ol3\node_modules\.bin\cl
eancss.cmd css/ol.css
2014-08-22 16:36:46,453 build/ol.js: node tasks/build.js buildcfg/ol.json build/
ol.js
info ol Parsing dependencies
info ol Compiling 330 sources

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
2014-08-22 16:36:59,792 build/ol.js: clean
2014-08-22 16:36:59,792 pake: build/ol.js: Command '['node', 'tasks/build.js', '
buildcfg/ol.json', 'build/ol.js']' returned non-zero exit status 8

It has generated the ol.css and info.json, but after that I am getting this issue. Can you let me know as we have corrected changes for generate-info.js for the paths, do we need to do some more changes in other files?

**Comment by ca0v** [comment]
Are there any up-to-date instructions on how to build OL3 on windows?  This is wasting so much time for so many people!

**Comment by probins** [comment]
can this one be closed?

**Comment by ahocevar** [comment]
Outdated, closing.
