### ISSUE TITLE
can't build in Windows 7 64bit

### ISSUE THREAD

**Issue by bicealyh** [openlayers/ol3#2925]
G:\ol3>build.py check                                                     
Traceback (most recent call last):                                                         File "G:\ol3\build.py", line 794, in <module>                               main()                                                                  File "G:\ol3\pake.py", line 442, in main                                    target.build(dry_run=options.dry_run)                                   File "G:\ol3\pake.py", line 109, in build                                   timestamp = max(timestamp, target.build(dry_run=dry_run))               File "G:\ol3\pake.py", line 109, in build                                   timestamp = max(timestamp, target.build(dry_run=dry_run))               File "G:\ol3\pake.py", line 124, in build                                   self.action(self)                                                       File "G:\ol3\build.py", line 519, in build_check_requires_timestamp         for key, child in root.children.iteritems()]                            File "G:\ol3\build.py", line 502, in build_re                               return re.compile('\\b' + self._build_re(key) + '\\b')                  File "C:\Python27\lib\re.py", line 190, in compile                          return _compile(pattern, flags)                                         File "C:\Python27\lib\re.py", line 243, in _compile                         p = sre_compile.compile(pattern, flags)                                 File "C:\Python27\lib\sre_compile.py", line 523, in compile                 groupindex, indexgroup                                                OverflowError: regular expression code size limit exceeded

**Comment by andreasrueedlinger** [comment]
Use module regex instead of re on line 794 in build.py (don't forget to install the module and to import it at the top of the file)

**Comment by fredj** [comment]
Outdated, closing.
