### ISSUE TITLE
Cannot run testsuite in Firefox 38

### ISSUE THREAD

**Issue by marcjansen** [openlayers/ol3#3765]
I cannot run our testsuite in Firefox 38. Opening http://localhost:3000/test/ shows a white page amnd results in the following error in the developer console:

```
ReferenceError: goog is not defined
    goog.events.listen(this, 'test', function() {});
```

which is a follow-up error of the error visible on the terminal:

```
url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Server.closure.Server.getMain (/home/marc/eclipse-kepler-workspace/ol3/tasks/serve.js:52:28)
    at Server._requestListener (/home/marc/eclipse-kepler-workspace/ol3/node_modules/closure-util/lib/server.js:148:23)
    at Manager.handleRequest (/home/marc/eclipse-kepler-workspace/ol3/node_modules/closure-util/node_modules/socket.io/lib/manager.js:565:28)
    at Server.<anonymous> (/home/marc/eclipse-kepler-workspace/ol3/node_modules/closure-util/node_modules/socket.io/lib/manager.js:119:10)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2109:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1967:22)
```

Steps to reproduce:

```bash
$ make cleanall && make build && make serve
// …
info serve Building examples.
info serve Parsing dependencies.
info serve Listening on http://localhost:3000/ (Ctrl+C to stop)
```

Then open http://localhost:3000/test/ and see the above error on the terminal.

```
node -v v0.10.38
npm -v 1.4.28
```

IE 11 and Chrome 41 are fine.

**Comment by marcjansen** [comment]
[Line 52](https://github.com/openlayers/ol3/blob/master/tasks/serve.js#L52) in `tasks/serve.js` is throwing the error, as `var referer = req.headers.referer;` evaluates to undefined in Firefox.

```js
      // …
      getMain: function(req) {
        var main;
        var query = url.parse(req.url, true).query;
        var referer = req.headers.referer;
        var pathName = url.parse(referer).pathname;
        if (pathName.indexOf('/test/') === 0) {
          // …
        } else if (pathName.indexOf('/test_rendering/') === 0) {
          // …
        } else {
          // …
        }
        return main;
      }
```

I don't know why FF doesn't send it, but this is the root of he above error. 

@tsauerwein introduced this check in 8e0c21eb580bbd7a659fa5088b9c145030f9b872 and I remember discussions of @tschaub and @elemoine about this different handling of requires.

Can anyone share a light what I/we should do about this?

**Comment by marcjansen** [comment]
Note to self, check if referers are disabled, possibly due to a setting in web developer toolbar. Maybe we should switch to an URL parameter instead?

**Comment by fredj** [comment]
@marcjansen It's working with firefox 43, can we close this issue?

**Comment by marcjansen** [comment]
@fredj, sure.
