### ISSUE TITLE
this.element_.appendChild(element) AND angularjs

### ISSUE THREAD

**Issue by thommydb** [openlayers/ol3#5922]
AngularJs not working when openlayer do this.element_.appendChild(element); (v3.16.0).
Openlayer v3.10.0 was compatible with this code line:
`
 goog.dom.append(/** @type {!Node} */ (this.element_), element);
`

the conflictive method is:

ol.Overlay.prototype.handleElementChanged

and console error:
`
angular.1.5.8.js:13920 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 
'Node'.
    at TypeError (native)
    at ol.Overlay.handleElementChanged (app/vendor/openLayers/3.12.0/ol-debug.js:68858:22)
    at boundListener app/vendor/openLayers/3.16.0/ol-debug.js:6131:21)
    at ol.events.EventTarget.dispatchEvent (/app/vendor/openLayers/3.16.0/ol-debug.js:6549:24)
    at ol.Object.notify (app/vendor/openLayers/3.16.0/ol-debug.js:6980:8)
    at ol.Object.set (app/vendor/openLayers/3.16.0/ol-debug.js:7000:12)
    at ol.Overlay.setElement (app/vendor/openLayers/3.16.0/ol-debug.js:68930:8)
    at new ol.Overlay (app/vendor/openLayers/3.16.0/ol-debug.js:68762:10)
    at Object.createOverlay (My class.js)
`

**Comment by bartvde** [comment]
did you see https://github.com/openlayers/ol3/pull/4492 ?

**Comment by thommydb** [comment]
sorry... thank you!

**Comment by fredj** [comment]
@thommydb can we close this issue?
